config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :questions do
    resources :answers, shallow: true do
      patch :choose_the_best, on: :member
    end
  end

  resources :attachments, only: [:destroy]

  root to: 'questions#index'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  belongs_to :user
  has_many :attachments, as: :attachable, dependent: :destroy

  validates :body, :question_id, :user_id, presence: true

  accepts_nested_attributes_for :attachments, reject_if: :all_blank, allow_destroy: true

  scope :from_the_best, -> { order('best DESC') }

  def choose_the_best
    unless best
      Answer.transaction do
        question.answers.where(best: true).update_all(best: false)
        update best: true
      end
    end
  end
end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
  belongs_to :attachable, polymorphic: true

  mount_uploader :file, FileUploader
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers, dependent: :destroy
  has_many :attachments, as: :attachable, dependent: :destroy
  belongs_to :user

  validates :title, :body, :user_id, presence: true

  accepts_nested_attributes_for :attachments, reject_if: :all_blank, allow_destroy: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :answers, dependent: :destroy
  has_many :questions, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def author?(work)
    work.user_id == id
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_answer, only: [:update, :destroy, :choose_the_best]

  def create
    @question = Question.find(params[:question_id])
    @answer = @question.answers.new(answer_params)
    @answer.user = current_user
    @answer.save
  end

  def update
    @answer.update(answer_params) if current_user.author?(@answer)
  end

  def destroy
    @answer.destroy if current_user.author?(@answer)
  end

  def choose_the_best
    @answer.choose_the_best if current_user.author?(@answer.question)
  end

  private

  def set_answer
    @answer = Answer.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body, attachments_attributes: [:file])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
  def destroy
    @attachment = Attachment.find(params[:id])
    @attachment.destroy if current_user.author?(@attachment.attachable)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  def index
    @questions = Question.all
  end

  def show
    @answer = @question.answers.build
    @answer.attachments.build
  end

  def new
    @question = Question.new
    @question.attachments.build
  end

  def create
    @question = Question.new(question_params)
    @question.user = current_user
    if @question.save
      flash[:notice] = 'Your question was successfully created.'
      redirect_to @question
    else
      render :new
    end
  end

  def update
    render :update if current_user.author?(@question) && @question.update(question_params)
  end

  def destroy
    if current_user.author?(@question)
      @question.destroy
      redirect_to questions_path
    else
      render :show
    end
  end

  private

  def set_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body, attachments_attributes: [:id, :file, :_destroy])
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/answers/_answer.html.slim
.answer id=dom_id(answer)
  - if user_signed_in? && current_user.author?(answer.question)
    p = link_to 'Choose the best', choose_the_best_answer_path(answer), method: :patch, remote: true,
            class: :choose_the_best
  p id="#{dom_id(answer)}-body" = answer.body
  .attachments
    p = render answer.attachments
  - if user_signed_in? && current_user.author?(answer)
    p class="edit-link" data-dom-id=dom_id(answer) = submit_tag 'Edit the answer'
    .edit-answer-form id="#{dom_id(answer)}-edit-form"
      = render 'answers/form', question: nil, answer: answer
    p = link_to 'Delete the answer', answer, method: :delete, remote: true

app/views/answers/_form.html.slim
p = form_for [question, answer], remote: true do |f|
  p = f.label :body, 'Your answer'
  .answer-errors
  p = f.text_area :body
  p = render 'attachments/form', f: f
  p = f.submit 'Confirm'

app/views/answers/choose_the_best.js.erb
var answer = $('#<%= dom_id(@answer) %>');
$('.answers').prepend(answer.prop('outerHTML'));
answer = answer.last();
answer.prop('outerHTML', '');

app/views/answers/create.js.erb
<% if @answer.errors.present? %>
  <% @answer.errors.full_messages.each do |message| %>
    $('.answer-errors').html('<%= j message %>');
  <% end %>
<% else %>
  $('.answers').append('<%= j render @answer %>');
  $('#answer_body').val('');
<% end %>

app/views/answers/destroy.js.erb
$('#<%= dom_id(@answer) %>').html('');

app/views/answers/update.js.erb
<% if @answer.errors.present? %>
  <% @answer.errors.full_messages.each do |message| %>
    $('.answer-errors').html('<%= j message %>');
  <% end %>
<% else %>
  $('#<%= dom_id(@answer) %>-body').html('<%= j @answer.body %>');
  $('#<%= dom_id(@answer) %>-edit-form').toggle();
<% end %>

app/views/application/_attachment_fields.html.slim
.nested-fields
  = f.label :file
  = f.file_field :file
  = link_to_remove_association 'Delete the file', f

app/views/attachments/_attachment.html.slim
div id=dom_id(attachment)
  p = link_to attachment.file.identifier, attachment.file.url
  - if user_signed_in? && current_user.author?(attachment.attachable)
    p = link_to 'Delete the file', attachment, method: :delete, remote: true

app/views/attachments/_form.html.slim
= f.fields_for :attachments do |a|
  p = render 'application/attachment_fields', f: a
  .links
    = link_to_add_association 'Add the file', f, :attachments

app/views/attachments/destroy.js.erb
$('#<%= dom_id(@attachment) %>').html('');

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : "StackOverflowClone"
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all", "data-turbolinks-track" => "reload"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag 'application'
    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js"


  body
    .navbar.navbar-default.navbar-static-top
        .container
          button.navbar-toggle type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse"
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.navbar-brand href="#"StackOverflowClone
          .navbar-collapse.collapse.navbar-responsive-collapse
            ul.nav.navbar-nav
              li= link_to "Link 1", "/path1"
              li= link_to "Link 2", "/path2"
              li= link_to "Link 3", "/path3"

    .container
      .row
        .col-lg-9
          = bootstrap_flash
          = yield
        .col-lg-3
          .well.sidebar-nav
            div id="login"
              - if user_signed_in?
                = "Hi #{current_user.email} "
                = link_to 'Sign out', destroy_user_session_path, method: :delete
              - else
                = link_to 'Sign in', new_user_session_path

      footer
        p &copy; Pavel Lavrinovich 2016

app/views/questions/_form.html.slim
p = form_for question, remote: remote do |f|
  p = f.label :title
  p = f.text_field :title
  p = f.label :body
  p = f.text_area :body
  p Attachments
  p = render 'attachments/form', f: f
  = f.submit 'Confirm'

app/views/questions/_question.html.slim
p = question.title
p = link_to 'Show', question_path(question), data: { turbolinks: false }

app/views/questions/index.html.slim
h1 Questions

p = link_to 'Ask a question', new_question_path

= render @questions

app/views/questions/new.html.slim
h1 New question
= render 'questions/form', question: @question, remote: false

app/views/questions/show.html.slim
h1 Question

.question
  h3 id="#{dom_id(@question)}-title" = @question.title
  p id="#{dom_id(@question)}-body" = @question.body

  - if user_signed_in? && current_user.author?(@question)
    p class="edit-link" data-dom-id=dom_id(@question) = submit_tag 'Edit the question'
    .edit-answer-form id="#{dom_id(@question)}-edit-form"
      = render 'questions/form', question: @question, remote: true
    p = link_to 'Delete the question', @question, method: :delete

h2 Attachments

.attachments
  p = render @question.attachments


h2 Answers

.answers
  = render @question.answers.from_the_best

= render 'answers/form', question: @question, answer: @answer

app/views/questions/update.js.erb
<% if @question.errors.present? %>
  <% @question.errors.full_messages.each do |message| %>
    $('.question-errors').html('<%= j message %>');
  <% end %>
<% else %>
  $('#<%= dom_id(@question) %>-title').html('<%= j @question.title %>');
  $('#<%= dom_id(@question) %>-body').html('<%= j @question.body %>');
  $('#<%= dom_id(@question) %>-edit-form').toggle();
<% end %>